// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.*;

public class GroupCreationTests extends TestBase{

    @Test
    public void createNewGroup() {
        openGroupPage();

        createGroup(new GroupData("Group 1", "Header Group", "Footer Group"));

    }

    @Test
    public void canCreateGroupWithEmptyName(){
        openGroupPage();
        createGroup(new GroupData());
    }

    @Test
    public void canCreateGroupWithNameOnly(){
        openGroupPage();
        var emptyGroup = new GroupData();
        var groupWithName = emptyGroup.withName("new name");
        createGroup(groupWithName);
    }
}
