// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;

public class GroupRemovalTests {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        driver.get("http://localhost/addressbook/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.name("user")).sendKeys("admin");
        driver.findElement(By.name("pass")).sendKeys("secret");
        driver.findElement(By.xpath("//input[@value=\'Login\']")).click();
    }

    @AfterEach
    public void tearDown() {
        driver.findElement(By.linkText("Logout")).click();
        driver.quit();
    }

    @Test
    public void groupRemovalTest() {
        {
            if (!isElementPresent(By.name("new"))) {
                driver.findElement(By.linkText("groups")).click();
            }
            if (!isElementPresent(By.name("selected[]"))){
                driver.findElement(By.name("new")).click();
                driver.findElement(By.name("group_name")).click();
                driver.findElement(By.name("group_name")).sendKeys("Group 1");
                driver.findElement(By.name("group_header")).sendKeys("Header Group");
                driver.findElement(By.name("group_footer")).sendKeys("Footer Group");
                driver.findElement(By.name("submit")).click();
                driver.findElement(By.linkText("group page")).click();
            }
            driver.findElement(By.name("selected[]")).click();
            driver.findElement(By.name("delete")).click();
            driver.findElement(By.linkText("group page")).click();

        }
    }
    private boolean isElementPresent(By locator) {
        try {
            driver.findElement(locator);
            return true;
        } catch (NoSuchElementException ex) {
            return false;
        }

    }

}
