// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

public class GroupRemovalTests extends TestBase{

    @Test
    public void groupRemovalTest() {
        {
            openGroupPage();
            if (isGroupPresent()){
                createGroup("Group_1", "Header_Group", "Footer_Group");
            }
            removeGroup();

        }
    }


}
