package tests;// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.*;

public class GroupCreationTests extends TestBase{

    @Test
    public void createNewGroup() {
        app.groups().createGroup(new GroupData("Group 1", "Header Group", "Footer Group"));

    }

    @Test
    public void canCreateGroupWithEmptyName(){
        app.groups().createGroup(new GroupData());
    }

    @Test
    public void canCreateGroupWithNameOnly(){
        app.groups().createGroup(new GroupData().withName("new name"));
    }
}
