package tests;// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.*;

public class GroupCreationTests extends TestBase{

    @Test
    public void createNewGroup() {
        int groupCount = app.groups().getCount();
        app.groups().createGroup(new GroupData("Group 1", "Header Group", "Footer Group"));
        int newGroupCount = app.groups().getCount();
        Assertions.assertEquals(groupCount + 1, newGroupCount);

    }

    @Test
    public void canCreateGroupWithEmptyName(){
        app.groups().createGroup(new GroupData());
    }

    @Test
    public void canCreateGroupWithNameOnly(){
        app.groups().createGroup(new GroupData().withName("new name"));
    }

    @Test
    public void canCreateMultipleGroups() {
        int n = 5;
        int groupCount = app.groups().getCount();

        for (int i = 0; i < n; i++){
            app.groups().createGroup(new GroupData(randomString(i), "Header Group", "Footer Group"));
        }
        int newGroupCount = app.groups().getCount();
        Assertions.assertEquals(groupCount + n, newGroupCount);

    }
}
